#undef TAPPING_TERM
#define TAPPING_TERM 150

#define USB_SUSPEND_WAKEUP_DELAY 0
#undef MOUSEKEY_INTERVAL
#define MOUSEKEY_INTERVAL 16

#undef MOUSEKEY_MAX_SPEED
#define MOUSEKEY_MAX_SPEED 10

#define SERIAL_NUMBER "5qbdw/PBpXWG"
#define LAYER_STATE_8BIT

#define RGB_MATRIX_STARTUP_SPD 60

